# Generated by Django 2.2.16 on 2020-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180328_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(null=True, upload_to='media/review/'),
        ),
    ]
